### ISSUE TITLE
Got "Device is not connected to external wifi AP" message when I'm connected 

### ISSUE THREAD

**Issue by rmescandon** [CanonicalLtd/UCWifiConnect#10]
- I'm connected with external AP and I can confirm I reach by ping www.terra.es.
- I see using 'nmcli d' that no device is managed (https://pastebin.canonical.com/182907/)
- However, if I try netman -check-connected-wifi, I get "Device is not connected to external wifi AP" (https://pastebin.canonical.com/182913/)

Testing in Raspberry PI with snaps wifi-connect, wifi-ap and network-manager installed

**Comment by knitzsche** [comment]
puzzling that netman reports wlan0 is not managed and yet you apparently can ping a web name. in my case, if my device is connected to external wifi and I then set the wlan0 interface to NOT be managed by netman, it drops from the external wifi:

knitzsche@localhost:~$ nmcli d
DEVICE  TYPE      STATE      CONNECTION        
wlan0   wifi      connected  astro_garden_2 20 
eth0    ethernet  unmanaged  --                
sit0    iptunnel  unmanaged  --                
lo      loopback  unmanaged  --                
knitzsche@localhost:~$ nmcli d set wlan0 managed n
HERE the connection drops and ssh fails.
in ssh over ethernet:
knitzsche@localhost:~$ nmcli d
DEVICE  TYPE      STATE      CONNECTION 
eth0    ethernet  unmanaged  --         
sit0    iptunnel  unmanaged  --         
lo      loopback  unmanaged  --         
wlan0   wifi      unmanaged  --         
knitzsche@localhost:~$ wifi-connect.netman -check-connected-wifi
Device is not connected to external wifi AP

Is it possible that you connected to the external AP through some means that does not involve network-manager? perhaps wlan0 was never managed by netman?

**Comment by knitzsche** [comment]
(strange strike-through font in previous comment...)

**Comment by rmescandon** [comment]
Forget. My bad. Wifi was set using wpa_suplicant and thus not managed by nmcli and even if tried to manage it using nmcli, nothing happened.
