### ISSUE TITLE
WifiConnect doesn't work if you have managed wireless through console-conf

### ISSUE THREAD

**Issue by arapulido** [CanonicalLtd/UCWifiConnect#26]
Steps to reproduce:

1) I install ubuntu core in my NUC
2) I go through console-conf, where I only configure wireless
3) I ssh into the system with my account (wireless)
4) snap refresh ; sudo reboot
5) install wifi-ap, network-manager and wifi-connect
6) create the socket folder
7) connect interfaces
8) Connect to an AP with wifi-connect.netman
9) nmcli c

Expected results:
The connection appears in the list of managed network-manager connections

Actual results:
nmcli c returns an empty output

**Comment by knitzsche** [comment]
So far (alpha) it only works when not connecting wifi at console-conf. One ssh/eth, sets the Mgmt ssid/passphrase and etc. I need to investigate the netplan/wifi/console-conf path.

**Comment by knitzsche** [comment]
Works on pi3 on the 0.8 alpha 1 snap release. 

(Although on pi3, configuring wifi from console-conf on pi does not work on first boot, you can run sudo console-conf after and redo the netplan config to set up wifi connection.)

We've embraced in netplan setting network manager as renderer for all networking (ethernets and wifis), thus sidestepping some issues that are said to exist with both networkd and netman active.  Network-manager snap will grow a config option to automate this.

Then, follow the README.md. Bottom line:
